### PR TITLE
Replace create_function() calls by closures

### PR DESCRIPTION
**Pull request by javiereguiluz**
Someone asked us to do this in the Symfony Standard (https://github.com/symfony/symfony-standard/issues/1102). Not sure if we should change the Standard Edition, but I thought we should fix that here.

### CODE REVIEW

**Comment by deguif** [comment]
`create_function` should be deprecated starting from `PHP 7.2`, so that PR also ensures compatibility with `PHP 8.0`

**Comment by chalasr** [comment]
👍 

Current output when using e.g. `symfony/installer` with php 7.2

>  Preparing project...

> PHP Deprecated:  Function create_function() is deprecated in /Volumes/HD/Sites/tests/lazy-command-defaultname/var/SymfonyRequirements.php on line 558

> Deprecated: Function create_function() is deprecated in /Volumes/HD/Sites/tests/lazy-command-defaultname/var/SymfonyRequirements.php on line 558
PHP Deprecated:  Function create_function() is deprecated in /Volumes/HD/Sites/tests/lazy-command-defaultname/var/SymfonyRequirements.php on line 707

> Deprecated: Function create_function() is deprecated in /Volumes/HD/Sites/tests/lazy-command-defaultname/var/SymfonyRequirements.php on line 707
 ✔  Symfony 3.3.9 was successfully installed.

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Comment by stof** [comment]
yeah, I think making the requirement checker incompatible with PHP 5.2 is fine now (it was needed years ago, to be able to report the issue about using a version of PHP being too old when 5.3 was the SF requirement)

**Pull request merged**
